### ISSUE TITLE
How can i add my own custom presets

### ISSUE THREAD

**Issue by AmbrocioIsaias2808** [kartik-v/yii2-widget-summernote#10]
Well like the title says, how can i add a diferent preset other than KrajeePresets?

Maybe the question is dumb but i can´t see where to declare this

![image](https://user-images.githubusercontent.com/44043979/110562490-321a2980-810f-11eb-9ccb-d185719ea704.png)

I mean, it will be cool to add the option to use the same pair-key-array  to just modify some properties, for example, in my case i only want to modify the height.

**Comment by kartik-v** [comment]
You can override presets and add your custom settings via `pluginOptions`
```php
echo Summernote::widget([
  'model' => $model,
  'attribute' => 'body',
  'useKrajeePresets' => true,
  'pluginOptions' => [
     'height' => 500
  ], //or something similar
])
```

**Comment by eramudeep** [comment]
i am also having a similar question.
but i am looking to add a custom button.
is it supporting to do so ?

i tried  :
`'pluginOptions' => [

                                                "buttons" => [
                                                    "hello" =>  new JsExpression(
                                                        " function (context) {
                                                                    var ui = $.summernote.ui;  
                                                                    var button = ui.button({
                                                                      contents: 'Hello',
                                                                      tooltip: 'hello',
                                                                      click: function () { 
                                                                        context.invoke('editor.insertText', 'hello');
                                                                      }
                                                                    }); 
                                                                    return button.render();   
                                                                  }
                                                        "
                                                    )
                                                ]
                                            ]`
