### ISSUE TITLE
demo link is broken

### ISSUE THREAD

**Issue by RodrigoDornelles** [kartik-v/yii2-widget-summernote#12]
![image](https://user-images.githubusercontent.com/29123479/119983356-6c6cc780-bf96-11eb-95e5-c5a67ab0482e.png)

**Comment by kartik-v** [comment]
The doc page was not ready earlier as the extension was not fully released. Now the version 1.0.0 of the extension has been released as well as the docs/demos pages. [Refer the docs/demos for yii2-editors here](https://demos.krajee.com/editors).
