### ISSUE TITLE
summernote inside modal, problem with help window

### ISSUE THREAD

**Issue by bobonov** [kartik-v/yii2-widget-summernote#14]
## Steps to reproduce the issue

When the summernote editor is inside a modal, opening the help and then closing it by clicking on the X dismiss both modal, while clicking outside help modal works as expected by closing only the help

## Expected behavior and actual behavior

The main modal should not close

## Environment

Browsers
tested in Google Chrome and  Mozilla Firefox for windows

Libraries

- jQuery version: 3.6.0
- yii2-editors version: @dev 1.0.1

## Isolating the problem
The bug happens consistently across all tested browsers
This bug happens when using yii2-editors without other plugins

**Comment by biladina** [comment]
#summernote/summernote#2993

**Comment by biladina** [comment]
#summernote/summernote#2993

**Comment by bobonov** [comment]
@biladina thanks that solved the issue
In pluginOption just add
`'pluginOptions' =>['dialogsInBody' => true, ....`
