### ISSUE TITLE
summernote editor overlapping

### ISSUE THREAD

**Issue by baltechies** [kartik-v/yii2-widget-summernote#18]
I am using Yii2 advance latest version 2.0.47. Bootstrap 5.
I have installed this and found that its overlapping other fields in form.

Any help?

<img width="1464" alt="Screenshot 2023-05-10 at 1 08 54 PM" src="https://github.com/kartik-v/yii2-editors/assets/13519944/36b0b10b-044a-4ce5-aa36-4639e3dcdcff">

**Comment by gs63875** [comment]
I am facing same issue. can you please have look @kartik-v @pappfer @gugoan 

![image](https://github.com/kartik-v/yii2-editors/assets/20258564/eba00b3c-f7d5-423b-bf92-313b651478d5)

**Comment by baltechies** [comment]
> I am facing same issue. can you please have look @kartik-v @pappfer @gugoan
> 
> ![image](https://user-images.githubusercontent.com/20258564/258996013-eba00b3c-f7d5-423b-bf92-313b651478d5.png)

I was able to resolve this by adding some style. @gs63875  You can add following style to site.css file.

```
.form-control.kv-editor-container{
    height: auto;
    padding:0;
}
```

**Comment by gs63875** [comment]
Works for me too.
Thank you @baltechies

**Comment by asadbekkuz** [comment]
I've a same problem with this. Just add Works for me too.
Thank you @baltechies

> > I am facing same issue. can you please have look @kartik-v @pappfer @gugoan
> > ![image](https://user-images.githubusercontent.com/20258564/258996013-eba00b3c-f7d5-423b-bf92-313b651478d5.png)
> 
> I was able to resolve this by adding some style. @gs63875 You can add following style to site.css file.
> 
> ```
> .form-control.kv-editor-container{
>     height: auto;
>     padding:0;
> }
> ```

I've a same problem. And work to me. Thank you
