### ISSUE TITLE
Style summernote.min.css can not be found

### ISSUE THREAD

**Issue by carlocaprini** [kartik-v/yii2-widget-summernote#2]
It seems that the style _summernote.min.css_ is not available anymore https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.12/summernote.min.css .

The field formatting options are therefore not displayed and the input content fails to be saved.

Can you please update the style link with a working one?

**Comment by kartik-v** [comment]
Resolved via latest commit.

**Comment by carlocaprini** [comment]
Tried it out, but I can not verify your fix. 
I am now getting a different error:

```
TypeError: $(...).kvSummernote is not a functioncreate:993:24
    <anonima> url_of_my_page:993
    jQuery 2
        mightThrow
        process
```
