### ISSUE TITLE
no network

### ISSUE THREAD

**Issue by buyu2272** [kartik-v/yii2-widget-summernote#4]
there no offline! my project don't allowed to connect network.

**Comment by kartik-v** [comment]
You can read about Yii2 Asset Manager in the Yii2 guide. In the Asset Manager component in your yii2 config file, configure this [extension's asset classes](https://github.com/kartik-v/yii2-editors/tree/master/src/assets) to point to your locally downloaded CSS/JS files instead of the CLOUD CDN.
