### ISSUE TITLE
Set Summernote plugin-specific options

### ISSUE THREAD

**Issue by fdbatista** [kartik-v/yii2-widget-summernote#9]
## Expected behavior and actual behavior

When I try to set some original Summernote options, like `airMode` , I get an error.
I was expecting to set this property while initializing the plugin, like this:

```php
Summernote::widget([
  'model' => $model,
  'attribute' => 'body',
  'useKrajeeStyle' => true,
  'useKrajeePresets' => true,
  'enableFullScreen' => false,
  'enableCodeView' => false,
  'enableAirMode' => true, //or something similar
])
```
Maybe I am looking at the wrong place. If so, how can I set those kind of plugin settings?

**Comment by MasterGHD** [comment]
The only way I solved this is by extending the original class:

```php
Class ExtSummerNote 
{
    public $pluginOptions = [
        'dialogsInBody' => true,
    ];
}

ExtSummerNote::widget([
  'model' => $model,
  'attribute' => 'body',
  'useKrajeeStyle' => true,
  'useKrajeePresets' => true,
  'enableFullScreen' => false,
  'enableCodeView' => false,
  'enableAirMode' => true, //or something similar
]);
`

**Comment by fdbatista** [comment]
@MasterGHD Thanx, I will try to extend it as well.
Have a good day!

**Comment by MasterGHD** [comment]
> @MasterGHD Thanx, I will try to extend it as well.
> Have a good day!

No problem and thank you!

Btw, I forgot to move the line "enableAirMode" to the property "pluginOptions".

Good work!

**Comment by kartik-v** [comment]
Hi you can set the plugin's properties in the widget via `pluginOptions`. There is no need to extend and create a new class ... following should work. Are you facing any issues?

```php
echo Summernote::widget([
  'model' => $model,
  'attribute' => 'body',
  'useKrajeeStyle' => true,
  'useKrajeePresets' => true,
  'enableFullScreen' => false,
  'enableCodeView' => false,
  'pluginOptions' => [
      'airMode' => true, //or something similar
  ]
]);
```

**Comment by MasterGHD** [comment]
> Hi you can set the plugin's properties in the widget via `pluginOptions`. There is no need to extend and create a new class ... following should work. Are you facing any issues?
> 
> ```
> echo Summernote::widget([
>   'model' => $model,
>   'attribute' => 'body',
>   'useKrajeeStyle' => true,
>   'useKrajeePresets' => true,
>   'enableFullScreen' => false,
>   'enableCodeView' => false,
>   'pluginOptions' => [
>       'airMode' => true, //or something similar
>   ]
> ]);
> ```

Good evening,

Yes, i had one issue. 

I couldn't set the option "dialogsInBody" on the pluginOptions. That's why I extended the class 

Also, the link for the summernote demo is broken.

**Comment by kartik-v** [comment]
For plugin options check the plugin release version. Currently extension has been updated to include latest stable version of the summernote and codemirror plugins. You may try with latest release.

The doc page was not ready earlier as the extension was not fully released. Now the version 1.0.0 of the extension has been released as well as the docs/demos pages. [Refer the docs/demos for yii2-editors here](https://demos.krajee.com/editors).
